// Verilog export (PLAN.md 5.3, 5.4): byte-identical to Wokwi's export of the
// reference design; the exported template behaves as designed under Icarus;
// and Icarus running Chiply's export of an edited design (one Wokwi never
// exported) matches Chiply's own simulator cycle by cycle.
#include "core/Drc.h"
#include "core/Netlist.h"
#include "core/Verilog.h"
#include "core/WokwiJson.h"
#include "sim/Simulator.h"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <random>
#include <sstream>

using namespace chiply;
namespace fs = std::filesystem;

namespace {

std::string readAll(const std::string& path)
{
    std::ifstream in(path, std::ios::binary);
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

std::string findTool(const char* name)
{
    for (const char* dir : {"/opt/homebrew/bin", "/usr/local/bin", "/usr/bin"})
        if (fs::exists(fs::path(dir) / name))
            return (fs::path(dir) / name).string();
    return {};
}

std::string run(const std::string& cmd)
{
    std::string out;
    if (FILE* f = popen(cmd.c_str(), "r")) {
        char buf[4096];
        while (std::size_t n = fread(buf, 1, sizeof buf, f))
            out.append(buf, n);
        pclose(f);
    }
    return out;
}

const std::string kRef = CHIPLY_REFERENCE_DIR;

// The reference design with the fixes Ken made in his copy: mux1..9 read
// the Q of the flip-flop they feed instead of their own output, and the
// unwired duplicate ttio5 is gone.
Document fixedReference()
{
    Document d = loadWokwi(readAll(kRef + "/wokwi_414123795172381697.diagram.json")).doc;
    const Netlist nl = Netlist::build(d, PartLibrary::builtin());
    for (int i = 1; i <= 9; ++i) {
        const std::string mux = "mux" + std::to_string(i);
        std::string flop;
        for (const NetPin& np : nl.nets[size_t(nl.netOf({mux, "OUT"}))].pins)
            if (nl.devices[size_t(np.device)].pinNames[size_t(np.pin)] == "D")
                flop = nl.devices[size_t(np.device)].partId;
        REQUIRE(!flop.empty());
        for (Wire& w : d.wires)
            if ((w.from.str() == mux + ":OUT" && w.to.str() == mux + ":A") || (w.to.str() == mux + ":OUT" && w.from.str() == mux + ":A")) {
                w.from = {flop, "Q"};
                w.to = {mux, "A"};
            }
    }
    d.parts.erase(std::remove_if(d.parts.begin(), d.parts.end(), [](const Part& p) { return p.id == "ttio5"; }), d.parts.end());
    return d;
}

} // namespace

TEST_CASE("export of the reference design is byte-identical to Wokwi's", "[verilog]")
{
    const Document d = loadWokwi(readAll(kRef + "/wokwi_414123795172381697.diagram.json")).doc;
    VerilogOptions o;
    o.moduleName = "tt_um_wokwi_414123795172381697";
    o.headerComment = "/* Automatically generated from https://wokwi.com/projects/414123795172381697 */";
    CHECK(writeVerilog(d, PartLibrary::builtin(), o) == readAll(kRef + "/tt_um_wokwi_414123795172381697.v"));
}

TEST_CASE("export details", "[verilog]")
{
    CHECK(defaultModuleName("my design-2") == "tt_um_my_design_2");
    Document d = loadWokwi(readAll(kRef + "/tt_template_354858054593504257.diagram.json")).doc;
    VerilogOptions o;
    o.moduleName = "tt_um_t";
    o.sourceName = "t.json";
    const std::string v = writeVerilog(d, PartLibrary::builtin(), o);
    CHECK(v.rfind("/* Automatically generated by Chiply from t.json */\n", 0) == 0);
    CHECK(v.find("module tt_um_t(") != std::string::npos);
    CHECK(v.find("  assign uio_out[0] = 1'b0;\n  assign uio_oe[0] = 1'b0;\n") != std::string::npos); // no bidir blocks
    // Parts with no cell cannot be exported.
    Part sr;
    sr.type = "wokwi-flip-flop-sr";
    sr.id = "sr1";
    d.parts.push_back(sr);
    CHECK_THROWS_AS(writeVerilog(d, PartLibrary::builtin(), o), ExportError);
}

TEST_CASE("the exported template behaves as designed under Icarus", "[verilog]")
{
    const std::string iverilog = findTool("iverilog"), vvp = findTool("vvp");
    if (iverilog.empty() || vvp.empty())
        SKIP("iverilog/vvp not installed");
    const fs::path dir = fs::temp_directory_path() / "chiply_verilog_template";
    fs::create_directories(dir);
    VerilogOptions o;
    o.moduleName = "tt_um_template";
    {
        std::ofstream f(dir / "dut.v");
        f << writeVerilog(loadWokwi(readAll(kRef + "/tt_template_354858054593504257.diagram.json")).doc,
                          PartLibrary::builtin(), o);
        std::ofstream tb(dir / "tb.v");
        tb << "`timescale 1ns/1ps\nmodule tb;\nreg [7:0] ui_in; wire [7:0] uo_out, uio_out, uio_oe; integer i, bad = 0;\n"
              "tt_um_template dut(.ui_in(ui_in), .uo_out(uo_out), .uio_in(8'h00), .uio_out(uio_out), .uio_oe(uio_oe),"
              " .ena(1'b1), .clk(1'b0), .rst_n(1'b1));\n"
              "initial begin\n  for (i = 0; i < 256; i = i + 1) begin\n    ui_in = i; #1;\n"
              "    if (uo_out !== {ui_in[7:4], ~ui_in[3:0]}) bad = bad + 1;\n  end\n"
              "  $display(\"bad=%0d\", bad); $finish;\nend\nendmodule\n";
    }
    const std::string build = run(iverilog + " -o " + (dir / "tb.vvp").string() + " " + (dir / "tb.v").string() + " "
                                  + (dir / "dut.v").string() + " " + kRef + "/cells.v 2>&1");
    INFO(build);
    REQUIRE(fs::exists(dir / "tb.vvp"));
    CHECK(run(vvp + " -n " + (dir / "tb.vvp").string()).find("bad=0") != std::string::npos);
}

TEST_CASE("Icarus on Chiply's export of an edited design matches Chiply's simulator", "[verilog]")
{
    const std::string iverilog = findTool("iverilog"), vvp = findTool("vvp");
    if (iverilog.empty() || vvp.empty())
        SKIP("iverilog/vvp not installed");
    const Document doc = fixedReference();
    {
        drc::Engine e;
        e.runFull(doc);
        REQUIRE(e.count(drc::Severity::Error) == 0); // the fixes clear every error
    }
    VerilogOptions o;
    o.moduleName = "tt_um_fixed";
    const fs::path dir = fs::temp_directory_path() / "chiply_verilog_fixed";
    fs::create_directories(dir);
    const int cycles = 2000;
    std::mt19937 rng(777);
    struct Vec {
        unsigned ui, uio;
        bool rstn;
    };
    std::vector<Vec> vec;
    for (int i = 0; i < cycles; ++i)
        vec.push_back({unsigned(rng() & 0xff), unsigned(rng() & 0xff), !(i < 4 || rng() % 100 == 0)});
    {
        std::ofstream f(dir / "dut.v");
        f << writeVerilog(doc, PartLibrary::builtin(), o);
        std::ofstream tb(dir / "tb.v");
        tb << "`timescale 1ns/1ps\nmodule tb;\nreg [7:0] ui_in, uio_in; reg clk = 0, rst_n = 0;\n"
              "wire [7:0] uo_out, uio_out, uio_oe;\n"
              "tt_um_fixed dut(.ui_in(ui_in), .uo_out(uo_out), .uio_in(uio_in), .uio_out(uio_out), .uio_oe(uio_oe),"
              " .ena(1'b1), .clk(clk), .rst_n(rst_n));\ninitial begin\n";
        for (const Vec& v : vec) {
            char line[256];
            std::snprintf(line, sizeof line,
                          "  ui_in = 8'h%02x; uio_in = 8'h%02x; rst_n = %d; #4 $display(\"%%b %%b %%b\", uo_out, uio_out, uio_oe);"
                          " #1 clk = 1; #4 $display(\"%%b %%b %%b\", uo_out, uio_out, uio_oe); #1 clk = 0;\n",
                          v.ui, v.uio, v.rstn ? 1 : 0);
            tb << line;
        }
        tb << "  $finish;\nend\nendmodule\n";
    }
    const std::string build = run(iverilog + " -o " + (dir / "tb.vvp").string() + " " + (dir / "tb.v").string() + " "
                                  + (dir / "dut.v").string() + " " + kRef + "/cells.v 2>&1");
    INFO(build);
    REQUIRE(fs::exists(dir / "tb.vvp"));
    std::istringstream expected(run(vvp + " -n " + (dir / "tb.vvp").string()));

    using namespace chiply::sim;
    const Netlist nl = Netlist::build(doc, PartLibrary::builtin());
    Options opt;
    opt.flopStart = FlopStart::Unknown;
    opt.board = false;
    opt.wokwiLogic = false;
    Simulator sim(nl, opt);
    std::map<int, std::string> uio;
    for (const Part& p : doc.parts)
        if (p.type == "board-tt-block-bidirectional-io")
            uio[std::stoi(p.attrs.value("verilogBit", std::string("0")))] = p.id;
    auto bus = [&](auto pinOfBit) {
        std::string s;
        for (int b = 7; b >= 0; --b)
            s += toChar(sim.value(pinOfBit(b)));
        return s;
    };
    int hard = 0, known = 0, bits = 0;
    std::string firstHard;
    for (int i = 0; i < cycles; ++i) {
        const Vec& v = vec[size_t(i)];
        for (int b = 0; b < 8; ++b) {
            sim.drive(PinRef{"ttin", "IN" + std::to_string(b)}, fromBool((v.ui >> b) & 1));
            sim.drive(PinRef{uio[b], "IN"}, fromBool((v.uio >> b) & 1));
        }
        sim.drive(PinRef{"ttin", "RST_N"}, fromBool(v.rstn));
        sim.drive(PinRef{"ttin", "CLK"}, V::L);
        REQUIRE(sim.settle());
        for (int phase = 0; phase < 2; ++phase) {
            if (phase == 1) {
                sim.drive(PinRef{"ttin", "CLK"}, V::H);
                REQUIRE(sim.settle());
            }
            std::string want;
            std::getline(expected, want);
            const std::string got = bus([](int b) { return PinRef{"ttout", "OUT" + std::to_string(b)}; }) + " "
                + bus([&](int b) { return PinRef{uio[b], "OUT"}; }) + " " + bus([&](int b) { return PinRef{uio[b], "OE"}; });
            for (std::size_t k = 0; k < want.size(); ++k) {
                if (want[k] == ' ')
                    continue;
                ++bits;
                const bool refKnown = want[k] == '0' || want[k] == '1';
                known += refKnown;
                if (refKnown && k < got.size() && got[k] != want[k]) {
                    ++hard;
                    if (firstHard.empty())
                        firstHard = "cycle " + std::to_string(i) + ": Chiply " + got + " vs Icarus " + want;
                }
            }
        }
    }
    INFO(firstHard);
    CHECK(known * 2 > bits);
    CHECK(hard == 0);
}

TEST_CASE("info.yaml patching keeps the file's layout", "[verilog]")
{
    // A Wokwi project's info.yaml (shape of tt-support-tools' template).
    const std::string wokwi = "# Tiny Tapeout project information (Wokwi project)\n"
                              "project:\n"
                              "  wokwi_id:     473800139156677633\n"
                              "  title:        \"Tiny Snake\"\n"
                              "  language:     \"Wokwi\" # other examples include SystemVerilog\n"
                              "  clock_hz:     10000   # Clock frequency in Hz\n"
                              "\n"
                              "pinout:\n"
                              "  ui[0]: \"speed\"\n";
    CHECK(patchInfoYaml(wokwi, "tt_um_snake", {"tt_um_snake.v", "cells.v"})
          == "# Tiny Tapeout project information (Wokwi project)\n"
             "project:\n"
             "  # wokwi_id:     473800139156677633  # exported from Chiply as Verilog\n"
             "  title:        \"Tiny Snake\"\n"
             "  language:     \"Verilog\" # other examples include SystemVerilog\n"
             "  top_module:   \"tt_um_snake\"\n"
             "  source_files:\n"
             "    - \"tt_um_snake.v\"\n"
             "    - \"cells.v\"\n"
             "  clock_hz:     10000   # Clock frequency in Hz\n"
             "\n"
             "pinout:\n"
             "  ui[0]: \"speed\"\n");
    // A Verilog project's info.yaml: values replaced in place.
    const std::string verilog = "project:\n"
                                "  language:     \"Verilog\" # comment\n"
                                "  top_module:  \"tt_um_old\"\n"
                                "  # List your project's source files here.\n"
                                "  source_files:\n"
                                "    - \"project.v\"\n"
                                "    - \"other.v\"\n"
                                "\n"
                                "pinout:\n";
    const std::string p = patchInfoYaml(verilog, "tt_um_new", {"tt_um_new.v", "cells.v"});
    CHECK(p == "project:\n"
               "  language:     \"Verilog\" # comment\n"
               "  top_module:  \"tt_um_new\"\n"
               "  # List your project's source files here.\n"
               "  source_files:\n"
               "    - \"tt_um_new.v\"\n"
               "    - \"cells.v\"\n"
               "\n"
               "pinout:\n");
    CHECK(infoYamlTopModule(verilog) == "tt_um_old");
    CHECK(infoYamlTopModule(wokwi).empty());
}

TEST_CASE("exporting a Tiny Tapeout project", "[verilog]")
{
    const fs::path dir = fs::temp_directory_path() / "chiply_tt_project";
    fs::remove_all(dir);
    fs::create_directories(dir / "test");
    {
        std::ofstream(dir / "info.yaml") << "project:\n  wokwi_id: 1\n  language: \"Wokwi\"\n";
        std::ofstream(dir / "test" / "Makefile") << "SRC_DIR = $(PWD)/../src\nPROJECT_SOURCES = project.v\n";
    }
    VerilogOptions o;
    o.moduleName = "tt_um_template";
    const auto done = exportTtProject(loadWokwi(readAll(kRef + "/tt_template_354858054593504257.diagram.json")).doc,
                                      PartLibrary::builtin(), dir.string(), o);
    CHECK(done.size() == 4); // .v, cells.v, info.yaml, Makefile
    CHECK(readAll((dir / "src" / "cells.v").string()) == readAll(kRef + "/cells.v"));
    CHECK(readAll((dir / "src" / "tt_um_template.v").string()).find("module tt_um_template(") != std::string::npos);
    CHECK(readAll((dir / "info.yaml").string()).find("top_module:   \"tt_um_template\"") != std::string::npos);
    CHECK(readAll((dir / "test" / "Makefile").string()).find("PROJECT_SOURCES = tt_um_template.v cells.v\n") != std::string::npos);
    fs::remove_all(dir);
}
