#include "vl/VerilatorChip.h"

#include "core/Blocks.h"
#include "core/PartLibrary.h"
#include "core/Verilog.h"
#include "sim/Simulator.h"

#include <dlfcn.h>
#include <unistd.h>
#include <sys/wait.h>

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <random>
#include <sstream>
#include <thread>
#include <vector>

namespace fs = std::filesystem;

namespace chiply::vl {

namespace {

constexpr int kAbi = 1;
constexpr const char* kModule = "tt_um_chiply";

std::string quote(const std::string& s)
{
    std::string r = "'";
    for (char c : s)
        r += (c == '\'') ? std::string("'\\''") : std::string(1, c);
    return r + "'";
}

// Runs a shell command; returns its exit status and output (stdout+stderr).
int run(const std::string& cmd, std::string* out)
{
    std::string text;
    FILE* f = popen((cmd + " 2>&1").c_str(), "r");
    if (!f) {
        if (out)
            *out = "cannot run: " + cmd;
        return -1;
    }
    char buf[4096];
    while (std::size_t n = fread(buf, 1, sizeof buf, f))
        text.append(buf, n);
    const int st = pclose(f);
    if (out)
        *out = text;
    return WIFEXITED(st) ? WEXITSTATUS(st) : -1;
}

std::string trim(std::string s)
{
    while (!s.empty() && (s.back() == '\n' || s.back() == '\r' || s.back() == ' '))
        s.pop_back();
    return s;
}

std::string findExecutable(const char* name, const std::vector<std::string>& extra)
{
    std::vector<std::string> dirs;
    if (const char* path = std::getenv("PATH")) {
        std::stringstream ss(path);
        for (std::string d; std::getline(ss, d, ':');)
            if (!d.empty())
                dirs.push_back(d);
    }
    dirs.insert(dirs.end(), extra.begin(), extra.end());
    for (const std::string& d : dirs) {
        const fs::path p = fs::path(d) / name;
        std::error_code ec;
        if (fs::is_regular_file(p, ec) && access(p.c_str(), X_OK) == 0)
            return p.string();
    }
    return {};
}

std::uint64_t fnv(const std::string& s, std::uint64_t h = 1469598103934665603ULL)
{
    for (unsigned char c : s) {
        h ^= c;
        h *= 1099511628211ULL;
    }
    return h;
}

std::string hex(std::uint64_t v)
{
    char b[17];
    std::snprintf(b, sizeof b, "%016llx", static_cast<unsigned long long>(v));
    return b;
}

void writeFile(const fs::path& p, const std::string& text)
{
    std::ofstream f(p, std::ios::binary);
    f << text;
    if (!f)
        throw BuildError("cannot write " + p.string());
}

#if defined(__APPLE__)
const char* kLibExt = ".dylib";
#else
const char* kLibExt = ".so";
#endif

std::vector<std::string> archFlags()
{
#if defined(__APPLE__) && defined(__aarch64__)
    return {"-arch", "arm64"};
#elif defined(__APPLE__) && defined(__x86_64__)
    return {"-arch", "x86_64"};
#else
    return {};
#endif
}

std::string joinArgs(const std::vector<std::string>& a)
{
    std::string s;
    for (const std::string& x : a)
        s += " " + quote(x);
    return s;
}

// The generated C entry points Chiply loads.
std::string wrapperSource(const VerilogNetMap& map)
{
    std::ostringstream o;
    o << "// Generated by Chiply. Do not edit.\n"
         "#include \"Vchip.h\"\n#include \"Vchip___024root.h\"\n#include \"verilated.h\"\n#include <cstdint>\n"
         "double sc_time_stamp() { return 0; }\n"
         "namespace { struct Model { VerilatedContext ctx; Vchip* top = nullptr; }; }\n"
         "extern \"C\" {\n"
         "int chiply_vl_abi() { return " << kAbi << "; }\n"
         "int chiply_vl_count() { return " << map.number.size() << "; }\n"
         "void* chiply_vl_new(int mode, unsigned long long seed) {\n"
         "  auto* m = new Model;\n"
         "  m->ctx.randReset(mode);\n"
         "  m->ctx.randSeed(int(seed & 0x7fffffffULL));\n"
         "  m->top = new Vchip(&m->ctx);\n"
         "  m->top->ena = 1;\n"
         "  return m;\n}\n"
         "void chiply_vl_free(void* p) { auto* m = static_cast<Model*>(p); delete m->top; delete m; }\n"
         "void chiply_vl_eval(void* p, unsigned char ui, unsigned char uio, unsigned char clk, unsigned char rst) {\n"
         "  Vchip* t = static_cast<Model*>(p)->top;\n"
         "  t->ui_in = ui; t->uio_in = uio; t->clk = clk; t->rst_n = rst; t->ena = 1;\n"
         "  t->eval();\n}\n"
         "void chiply_vl_read(void* p, unsigned char* o) {\n"
         "  const auto* r = static_cast<Model*>(p)->top->rootp;\n";
    for (std::size_t i = 0; i < map.number.size(); ++i)
        o << "  o[" << i << "] = r->" << kModule << "__DOT__net" << map.number[i] << " & 1;\n";
    o << "}\n}\n";
    return o.str();
}

class VerilatorBackend : public sim::ChipBackend {
public:
    VerilatorBackend(void* lib, std::vector<int> nets, std::string name)
        : m_nets(std::move(nets))
        , m_name(std::move(name))
    {
        m_new = reinterpret_cast<void* (*)(int, unsigned long long)>(dlsym(lib, "chiply_vl_new"));
        m_free = reinterpret_cast<void (*)(void*)>(dlsym(lib, "chiply_vl_free"));
        m_eval = reinterpret_cast<void (*)(void*, unsigned char, unsigned char, unsigned char, unsigned char)>(
            dlsym(lib, "chiply_vl_eval"));
        m_read = reinterpret_cast<void (*)(void*, unsigned char*)>(dlsym(lib, "chiply_vl_read"));
        if (!m_new || !m_free || !m_eval || !m_read)
            throw BuildError("the chip library is missing entry points");
    }
    ~VerilatorBackend() override
    {
        if (m_model)
            m_free(m_model);
        // The library stays loaded: dlclose of a Verilated model's library
        // is not safe while its statics may still be referenced.
    }
    std::string name() const override { return m_name; }
    const std::vector<int>& nets() const override { return m_nets; }
    void reset(sim::FlopStart start, std::uint64_t seed) override
    {
        if (m_model)
            m_free(m_model);
        if (seed == 0)
            seed = std::random_device{}();
        m_model = m_new(start == sim::FlopStart::Zero ? 0 : 2, seed);
    }
    void eval(std::uint8_t ui, std::uint8_t uio, bool clk, bool rstN) override
    {
        if (!m_model)
            reset(sim::FlopStart::Random, 0);
        m_eval(m_model, ui, uio, clk, rstN);
    }
    void read(std::vector<std::uint8_t>& v) override
    {
        v.resize(m_nets.size());
        if (m_model && !v.empty())
            m_read(m_model, v.data());
    }

private:
    std::vector<int> m_nets;
    std::string m_name;
    void* m_model = nullptr;
    void* (*m_new)(int, unsigned long long) = nullptr;
    void (*m_free)(void*) = nullptr;
    void (*m_eval)(void*, unsigned char, unsigned char, unsigned char, unsigned char) = nullptr;
    void (*m_read)(void*, unsigned char*) = nullptr;
};

std::mutex g_buildMutex; // one build at a time per process (shared cache dirs)

} // namespace

std::string defaultCacheDir()
{
    if (const char* env = std::getenv("CHIPLY_VL_CACHE"); env && *env)
        return env;
    const char* home = std::getenv("HOME");
#if defined(__APPLE__)
    return (fs::path(home ? home : "/tmp") / "Library" / "Caches" / "Chiply" / "verilator").string();
#else
    if (const char* xdg = std::getenv("XDG_CACHE_HOME"))
        return (fs::path(xdg) / "chiply" / "verilator").string();
    return (fs::path(home ? home : "/tmp") / ".cache" / "chiply" / "verilator").string();
#endif
}

std::optional<Tools> findTools(std::string* why)
{
    Tools t;
    const std::vector<std::string> extra = {"/opt/homebrew/bin", "/usr/local/bin", "/opt/local/bin", "/usr/bin"};
    if (const char* env = std::getenv("CHIPLY_VERILATOR"); env && *env)
        t.verilator = env;
    else
        t.verilator = findExecutable("verilator", extra);
    if (t.verilator.empty()) {
        if (why)
            *why = "Verilator is not installed (brew install verilator)";
        return std::nullopt;
    }
    std::string out;
    if (run(quote(t.verilator) + " --version", &out) != 0) {
        if (why)
            *why = "cannot run " + t.verilator + ": " + trim(out);
        return std::nullopt;
    }
    {
        std::istringstream in(out);
        std::string word;
        in >> word >> t.version; // "Verilator 5.050 ..."
    }
    if (run(quote(t.verilator) + " --getenv VERILATOR_ROOT", &out) != 0 || trim(out).empty()) {
        if (why)
            *why = "cannot find VERILATOR_ROOT of " + t.verilator;
        return std::nullopt;
    }
    t.root = trim(out);
    if (!fs::exists(fs::path(t.root) / "include" / "verilated.cpp")) {
        if (why)
            *why = "Verilator runtime sources not found in " + t.root;
        return std::nullopt;
    }
#if defined(__APPLE__)
    t.cxx = fs::exists("/usr/bin/c++") ? "/usr/bin/c++" : "";
#else
    t.cxx = findExecutable("c++", extra);
    if (t.cxx.empty())
        t.cxx = findExecutable("g++", extra);
#endif
    if (t.cxx.empty()) {
        if (why)
            *why = "no C++ compiler found (on macOS: xcode-select --install)";
        return std::nullopt;
    }
    return t;
}

std::shared_ptr<sim::ChipBackend> buildChip(const Document& doc, const Tools& tools, const BuildOptions& opt,
                                            BuildInfo* info)
{
    const auto t0 = std::chrono::steady_clock::now();
    auto status = [&](const std::string& s) {
        if (opt.status)
            opt.status(s);
    };
    auto checkCancel = [&] {
        if (opt.cancel && opt.cancel->load())
            throw BuildError("cancelled");
    };
    VerilogOptions vo;
    vo.moduleName = kModule;
    vo.headerComment = "/* Generated by Chiply for the Verilator backend */";
    VerilogNetMap map;
    const std::string verilog = writeVerilog(doc, PartLibrary::builtin(), vo, &map);
    const std::string wrapper = wrapperSource(map);
    const std::vector<std::string> arch = archFlags();
    const std::vector<std::string> cflags = {"-std=c++20", "-O1", "-fPIC", "-w"};
    const std::string flagKey = joinArgs(arch) + joinArgs(cflags) + tools.cxx;

    const fs::path cache = opt.cacheDir.empty() ? fs::path(defaultCacheDir()) : fs::path(opt.cacheDir);
    // Custom blocks: their Verilog goes in too (and into the cache key).
    const std::vector<std::string> blockFiles = blockSources(doc);
    std::string blockText;
    for (const std::string& f : blockFiles) {
        std::ifstream bf(f, std::ios::binary);
        std::stringstream bs;
        bs << bf.rdbuf();
        blockText += f + "\n" + bs.str();
    }
    const std::string key = hex(fnv(verilog + wrapper + chiplyCellsV() + blockText + tools.version + tools.root + flagKey + std::to_string(kAbi)));
    const fs::path dir = cache / key;
    const fs::path lib = dir / (std::string("libchip") + kLibExt);
    const std::string name = "Verilator " + tools.version;

    std::lock_guard<std::mutex> lock(g_buildMutex);
    bool fromCache = fs::exists(lib);
    if (!fromCache) {
        // Build in a private directory and move it into place at the end, so
        // concurrent builds (two Chiply processes, parallel tests) never see
        // or damage a half-built entry.
        std::error_code ec;
        if (fs::exists(dir))
            fs::remove_all(dir, ec); // an incomplete entry (no library): rebuild it
        const fs::path work = cache / (key + ".tmp-" + std::to_string(getpid()) + "-" + hex(std::random_device{}()));
        struct Cleanup {
            fs::path p;
            ~Cleanup()
            {
                std::error_code e;
                fs::remove_all(p, e); // gone already after a successful move
            }
        } cleanup{work};
        fs::create_directories(work / "obj");
        writeFile(work / "chip.v", verilog);
        writeFile(work / "cells.v", ttCellsV());
        writeFile(work / "chiply_cells.v", chiplyCellsV());
        writeFile(work / "wrapper.cpp", wrapper);

        status("Verilating the chip");
        checkCancel();
        std::string log;
        std::string vcmd = quote(tools.verilator) + " --cc --top-module " + kModule
            + " --prefix Vchip -Wno-fatal -Wno-lint -Wno-style --public-flat-rw --x-assign unique --x-initial unique"
              " -O3 --Mdir "
            + quote((work / "obj").string()) + " " + quote((work / "chip.v").string()) + " "
            + quote((work / "cells.v").string()) + " " + quote((work / "chiply_cells.v").string());
        for (const std::string& f : blockFiles)
            vcmd += " " + quote(f) + " -I" + quote(fs::path(f).parent_path().string());
        if (run(vcmd, &log) != 0) {
            BuildError e("Verilator failed");
            e.log = log;
            throw e;
        }
        checkCancel();

        // The Verilator runtime is compiled once per Verilator / compiler.
        const fs::path rt = cache / ("runtime-" + hex(fnv(tools.root + tools.version + flagKey)));
        fs::create_directories(rt);
        std::vector<std::pair<fs::path, fs::path>> units; // source -> object
        const std::string inc = " -I" + quote(tools.root + "/include") + " -I" + quote(tools.root + "/include/vltstd");
        for (const char* r : {"verilated.cpp", "verilated_threads.cpp"})
            if (!fs::exists(rt / (std::string(r) + ".o")))
                units.push_back({fs::path(tools.root) / "include" / r, work / (std::string(r) + ".o")});
        for (const auto& e : fs::directory_iterator(work / "obj"))
            if (e.path().extension() == ".cpp")
                units.push_back({e.path(), work / "obj" / (e.path().stem().string() + ".o")});
        units.push_back({work / "wrapper.cpp", work / "wrapper.o"});

        status("Compiling " + std::to_string(units.size()) + " files");
        std::atomic<std::size_t> next{0}, done{0};
        std::mutex errMutex;
        std::string errLog;
        const unsigned jobs = opt.jobs > 0 ? unsigned(opt.jobs) : std::max(1u, std::thread::hardware_concurrency());
        std::vector<std::thread> pool;
        for (unsigned j = 0; j < jobs; ++j)
            pool.emplace_back([&] {
                for (;;) {
                    const std::size_t i = next++;
                    if (i >= units.size() || (opt.cancel && opt.cancel->load()))
                        return;
                    {
                        std::lock_guard<std::mutex> g(errMutex);
                        if (!errLog.empty())
                            return;
                    }
                    std::string out;
                    const std::string cmd = quote(tools.cxx) + joinArgs(arch) + joinArgs(cflags) + inc + " -I"
                        + quote((work / "obj").string()) + " -c " + quote(units[i].first.string()) + " -o "
                        + quote(units[i].second.string());
                    if (run(cmd, &out) != 0) {
                        std::lock_guard<std::mutex> g(errMutex);
                        if (errLog.empty())
                            errLog = units[i].first.filename().string() + ":\n" + out;
                    }
                    const std::size_t n = ++done;
                    status("Compiled " + std::to_string(n) + " of " + std::to_string(units.size()) + " files");
                }
            });
        for (std::thread& t : pool)
            t.join();
        checkCancel();
        if (!errLog.empty()) {
            BuildError e("compiling the chip failed");
            e.log = errLog;
            throw e;
        }
        // Share the runtime objects (rename is atomic; any copy is complete).
        for (const char* r : {"verilated.cpp", "verilated_threads.cpp"})
            if (fs::exists(work / (std::string(r) + ".o")))
                fs::rename(work / (std::string(r) + ".o"), rt / (std::string(r) + ".o"));
        status("Linking");
        std::string objs;
        for (const auto& e : fs::directory_iterator(work / "obj"))
            if (e.path().extension() == ".o")
                objs += " " + quote(e.path().string());
        objs += " " + quote((work / "wrapper.o").string()) + " " + quote((rt / "verilated.cpp.o").string()) + " "
            + quote((rt / "verilated_threads.cpp.o").string());
        const fs::path tmpLib = work / (std::string("libchip.tmp") + kLibExt);
        const std::string lcmd = quote(tools.cxx) + joinArgs(arch) + " -shared" + objs + " -o " + quote(tmpLib.string())
#if !defined(__APPLE__)
            + " -lpthread"
#endif
            ;
        if (run(lcmd, &log) != 0) {
            BuildError e("linking the chip failed");
            e.log = log;
            throw e;
        }
        fs::rename(tmpLib, work / lib.filename());
        fs::rename(work, dir, ec); // fails if another build got there first: use that one
        if (ec)
            fs::remove_all(work, ec);
    }

    status("Loading the chip");
    void* handle = dlopen(lib.c_str(), RTLD_NOW | RTLD_LOCAL);
    if (!handle)
        throw BuildError(std::string("cannot load the chip: ") + dlerror());
    auto abi = reinterpret_cast<int (*)()>(dlsym(handle, "chiply_vl_abi"));
    auto count = reinterpret_cast<int (*)()>(dlsym(handle, "chiply_vl_count"));
    if (!abi || !count || abi() != kAbi || count() != int(map.number.size()))
        throw BuildError("the cached chip library does not match; delete " + dir.string());
    auto backend = std::make_shared<VerilatorBackend>(handle, map.netlistIndex, name);
    if (info) {
        info->fromCache = fromCache;
        info->library = lib.string();
        info->seconds = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    }
    return backend;
}

} // namespace chiply::vl
